#!/usr/bin/env bash
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor)(\([^)]+\))?: [^\n]+$"; then
    echo "Aborting commit. Your commit message is invalid. Please follow conventional commit message format." >&2
    exit 1
fi
if [ "$(head -1 "$1" | head -c 51 | wc -c)" -gt 50 ]; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi